### ISSUE TITLE
关于模型训练的一些问题

### ISSUE THREAD

**Issue by su-sang** [Nomination-NRB/VisualBilibili#1]
作者您好，我想自己进行模型的训练，请问我应该怎么做呢？希望您能指点一二，十分感谢！

**Comment by Nomination-NRB** [comment]
关于模型训练我开了个新仓库，所有的文件都有，但是模型比较简单，你可以根据你自己的想法来修改，仓库地址：https://github.com/Nomination-NRB/SentimentClassify
如果训练过程有问题的话，直接在那个仓库提issues就好

**Comment by Nomination-NRB** [comment]
> 作者您好，我想自己进行模型的训练，请问我应该怎么做呢？希望您能指点一二，十分感谢！

关于模型训练我开了个新仓库，所有的文件都有，但是模型比较简单，你可以根据你自己的想法来修改，仓库地址：https://github.com/Nomination-NRB/SentimentClassify
如果训练过程有问题的话，直接在那个仓库提issues就好

**Comment by su-sang** [comment]
十分感谢！
